spring.application.name=auth-service
server.port=8001
spring.data.mongodb.uri=mongodb://mongodb:27017/authdb
jwt.secret=shubhranshu_satpathy_hotel_microservise_2026
eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka